### ISSUE TITLE
PUNYA NELSEN

### ISSUE THREAD

**Issue by NlsnHerlan** [HarisMI40/12_RPL_Tugas#13]
https://github.com/NlsnHerlan/Latihan/tree/main/Nelsen%20PUNYA

**Comment by NlsnHerlan** [comment]
https://github.com/NlsnHerlan/Latihan/tree/main/Nelsen%20PUNYA

**Comment by NlsnHerlan** [comment]
https://github.com/NlsnHerlan/Latihan/tree/main/Nelsen%20PUNYA

**Comment by RedIrfan** [comment]
gg

**Comment by RedIrfan** [comment]
tadi titlenya kenapa bang

**Comment by RidwanAnnV** [comment]
GG titlenya malah link

**Comment by rhmatt-code** [comment]
bruh pisan kang

**Comment by IbnuSulaiman14** [comment]
woi link

**Comment by NlsnHerlan** [comment]
KOMEN DOANG KGK FOLLOW ANAK 45u

**Comment by IbnuSulaiman14** [comment]
diserang bjirka
